### ISSUE TITLE
Add deploy key

### ISSUE THREAD

**Issue by retog** [plazi/plazi.org#1]
Add the following deploy key with write permissions to allow automated deployments:

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDABQdcIQiVkPrwb6LD4vB1XXg3Tc4ql0zRl3xkRfH9y4nL2xcrkYd72jJkuYFJWCMjOiacSyPaDsve2noGujdZRPeJa2Y+/bKL1vkkuk6FhCDXic0d/1+Qn2qPH/Aypx6hKYWbo4GG3Uuda2NMDxN6wzFI9mQ3aOjCzaSoeVGSxVpquQ+EFZtS2dPuzytBKsKVcGSmx1xZjGMr2Gld1t3STCU30YsOYIOPHa95thhpIkg2XOnnzHYdzNJrctylKr1KY+kTCjxH8hAV5DO6nFQAcMjCGys0gApHFAk9XlDIVfottOGDgKTYjuzP4G8y/v9AjEoO1HbkLzRTWXpiHqUJ actions@GITHUB
```

**Comment by myrmoteras** [comment]
@retog here it is
![image](https://user-images.githubusercontent.com/4609956/129266072-83be6add-baaf-4770-9fff-e0601edc5bca.png)

**Comment by retog** [comment]
That's the wrong repo. Please add the deploy key to this (plazi.org) repository, not to plaziWebsite

**Comment by retog** [comment]
Great, it works now!
